import type { OfferCreatorData } from "~/types/offer";

export const getArticle = (word: string) => {
  if (!word) return "a";
  const firstChar = word.toLowerCase().charAt(0);
  return ["a", "e", "i", "o", "u"].includes(firstChar) ? "an" : "a";
};

export const generateOfferText = (f: OfferCreatorData) =>
  [
    `# ${f.packageName || "[Package Name]"}`,
    "",
    "",
    "If you’re struggling with:",
    "",
    f.painPoint1 ? `- ${f.painPoint1}` : "",
    f.painPoint2 ? `- ${f.painPoint2}` : "",
    f.painPoint3 ? `- ${f.painPoint3}` : "",
    f.painPoint4 ? `- ${f.painPoint4}` : "",
    f.painPoint5 ? `- ${f.painPoint5}` : "",
    "",
    " ",
    `…then buying **${f.packageName || "[Package Name]"}** will fix that.`,
    "",
    "## Does This Sound Like You?",
    "",
    f.symptom1 ? `- ${f.symptom1}` : "",
    f.symptom2 ? `- ${f.symptom2}` : "",
    f.symptom3 ? `- ${f.symptom3}` : "",
    f.symptom4 ? `- ${f.symptom4}` : "",
    " ",
    `If so, you’re exactly who **${f.packageName || "[Package Name]"}** was built for.`,
    "",
    f.roleOverloadDetails
      ? `You’re juggling ${f.roleOverloadDetails}, and it’s impossible to make real progress when everything depends on you.`
      : "",
    "",
    `That's why ${f.useWeLanguage ? "we" : "I"} created **${f.packageName || "[Package Name]"}** – to solve **${f.coreProblem || "[core problem]"}** once and for all.`,
    "",
    "## The Promise",
    "",
    `${f.useWeLanguage ? "We help" : "I help"} you achieve **${f.primaryOutcome || "[primary outcome]"}** by delivering **${f.coreMechanism || "[core mechanism]"}** for **${f.buyerType || "[buyer type]"}** in **${f.niche || "[niche]"}**, using **${f.toolsOrMethod || "[tools/method]"}**.`,
    " ",
    "In other words:",
    "",
    `**${f.useWeLanguage ? "We help" : "I help"} you get ${f.simpleOutcome || "[simple outcome]"} without ${f.bigObstacle || "[big obstacle]"}.**`,
    "",
    "## How It Works",
    "",
    `1. You complete ${getArticle(f.onboardingFormName)} ${f.onboardingFormName || "[onboarding form]"} `,
    `2. ${f.useWeLanguage ? "We meet" : "I meet"} with you for a ${f.workshopLength || "[workshop length]"} workshop`,
    `3. ${f.useWeLanguage ? "We" : "I"} build your **${f.packageName || "[Package Name]"}** ${f.buildStyle || "[build style]"} `,
    "",
    "## You Walk Away With",
    "",
    f.deliverable1 ? `1. ${f.deliverable1}` : "",
    f.deliverable2 ? `2. ${f.deliverable2}` : "",
    f.deliverable3 ? `3. ${f.deliverable3}` : "",
    f.optionalDeliverable4 ? `4. ${f.optionalDeliverable4}` : "",
    " ",
    f.clientPreferredWork || f.clientPainfulWork
      ? `In the end, you get to focus on **${f.clientPreferredWork || "[the work you enjoy]"}**, instead of **${f.clientPainfulWork || "[the work you hate]"}**.`
      : "",
    "",
    "## Who It’s For",
    "",
    `This is for **${f.buyerType || "[buyer type]"}** who want to:`,
    "",
    f.goal1 ? `- ${f.goal1}` : "",
    f.goal2 ? `- ${f.goal2}` : "",
    f.goal3 ? `- ${f.goal3}` : "",
    f.goal4 ? `- ${f.goal4}` : "",
    "",
    "## What’s Included",
    "",
    `### 1. ${f.deliverableBlock1Title || "[Block 1 Title]"}`,
    "",
    `${f.useWeLanguage ? "We" : "I"} ${f.actionVerb1 || "[action verb]"} your ${f.component1 || "[component]"} so you can ${f.outcome1 || "[outcome]"}.`,
    "",
    "Includes:",
    "",
    f.subItemA ? `- ${f.subItemA}` : "",
    f.subItemB ? `- ${f.subItemB}` : "",
    f.subItemC ? `- ${f.subItemC}` : "",
    " ",
    f.outcomeStatement1 ? `Outcome: ${f.outcomeStatement1}` : "",
    "",
    `### 2. ${f.deliverableBlock2Title || "[Block 2 Title]"}`,
    "",
    `${f.useWeLanguage ? "We" : "I"} ${f.actionVerb2 || "[action verb]"} your ${f.component2 || "[component]"} so ${f.outcome2 || "[outcome]"}.`,
    "",
    "Includes:",
    "",
    f.subItemD ? `- ${f.subItemD}` : "",
    f.subItemE ? `- ${f.subItemE}` : "",
    f.subItemF ? `- ${f.subItemF}` : "",
    " ",
    f.outcomeStatement2 ? `Outcome: ${f.outcomeStatement2}` : "",
    "",
    `### 3. ${f.deliverableBlock3Title || "[Block 3 Title]"}`,
    "",
    `${f.useWeLanguage ? "We" : "I"} ${f.actionVerb3 || "[action verb]"} your ${f.component3 || "[component]"} using ${f.toolsOrProcess || "[tools/process]"}.`,
    "",
    "Includes:",
    "",
    f.subItemG ? `- ${f.subItemG}` : "",
    f.subItemH ? `- ${f.subItemH}` : "",
    f.subItemI ? `- ${f.subItemI}` : "",
    " ",
    f.outcomeStatement3 ? `Outcome: ${f.outcomeStatement3}` : "",
    "",
    "## Pricing Options",
    "",
    f.monthlyPrice
      ? `**Option A – Monthly Retainer**  \n$${f.monthlyPrice}/month`
      : "",
    " ",
    f.setupPrice || f.mgmtPrice
      ? `**Option B – Setup + Management**  \nSetup: $${f.setupPrice || "[setup price]"}  \nManagement: $${f.mgmtPrice || "[management price]"}/month`
      : "",
    " ",
    f.basePrice || f.commissionPercent
      ? `**Option C – Retainer + Performance**  \n$${f.basePrice || "[base price]"}/month + ${f.commissionPercent || "[%]"}% of ${f.commissionTrigger || "[commission trigger]"}`
      : "",
    "",
    "## Are You Ready?",
    "",
    `Ready to get **${f.primaryOutcome || "[primary outcome]"}** for **${f.niche || "[niche]"}** without **${f.bigObstacle || "[big obstacle]"}**?`,
    `Let’s schedule your discovery call and map out your first ${f.timeFrame || "[time frame]"}.`,
  ]
    .filter(Boolean)
    .join("\n");
