import type { OfferCreatorData, OfferFieldSection } from "~/types/offer";

export const DEFAULT_OFFER_FORM: OfferCreatorData = {
  useWeLanguage: false,
  packageName: "Outbound Growth Engine",
  painPoint1: "Inconsistent lead generation",
  painPoint2: "Unpredictable sales pipeline",
  painPoint3: "Manual prospecting takes too much time",
  painPoint4: "Low response rates from cold outreach",
  painPoint5: "Difficulty identifying qualified prospects",
  symptom1: "Working 60+ hours but revenue stays flat",
  symptom2: "Feast or famine sales cycles",
  symptom3: "Most of your time spent chasing leads",
  symptom4: "Declining conversion rates from referrals",
  roleOverloadDetails: "sales, delivery, operations, and strategy all at once",
  coreProblem: "inconsistent, unpredictable pipeline and sales",
  primaryOutcome: "a consistent flow of qualified conversations",
  coreMechanism: "a simple, automated outbound system",
  buyerType: "B2B service businesses",
  niche: "industrial and professional services",
  toolsOrMethod: "smart data, targeted messaging, and light automation",
  simpleOutcome: "booked meetings with real buyers",
  bigObstacle: "spending all day chasing leads",
  onboardingFormName: "quick onboarding form",
  workshopLength: "60–90 minute",
  buildStyle: "live with you on the call",
  deliverable1: "Complete prospect database with contact details",
  deliverable2: "Automated email sequences for follow-up",
  deliverable3: "Custom CRM setup and training",
  optionalDeliverable4: "Monthly performance review calls",
  clientPreferredWork: "the creative and strategic work you actually enjoy",
  clientPainfulWork: "manual follow-ups and chasing cold leads",
  goal1: "Generate 5-10 qualified leads per month",
  goal2: "Reduce time spent on prospecting by 70%",
  goal3: "Increase conversion rates from outreach",
  goal4: "Build a predictable sales pipeline",
  deliverableBlock1Title: "Prospect Research & Database Setup",
  actionVerb1: "research and organize",
  component1: "target prospect database",
  outcome1: "focus your efforts on the right people",
  subItemA: "Industry-specific prospect list (500+ contacts)",
  subItemB: "Contact verification and enrichment",
  subItemC: "CRM setup with automated scoring",
  outcomeStatement1: "You'll have a qualified database of prospects ready to contact",
  deliverableBlock2Title: "Outreach System & Messaging",
  actionVerb2: "create and optimize",
  component2: "messaging and outreach sequences",
  outcome2: "your messages get opened and responded to",
  subItemD: "Email templates with high response rates",
  subItemE: "LinkedIn connection and follow-up sequences",
  subItemF: "A/B testing framework for optimization",
  outcomeStatement2: "You'll have proven messaging that consistently generates responses",
  deliverableBlock3Title: "Automation & Follow-up Systems",
  actionVerb3: "implement and configure",
  component3: "automated follow-up systems",
  toolsOrProcess: "email automation and CRM workflows",
  subItemG: "Automated email drip campaigns",
  subItemH: "Follow-up reminders and scheduling",
  subItemI: "Performance tracking and reporting",
  outcomeStatement3: "You'll have a system that works while you focus on closing deals",
  monthlyPrice: "2500",
  setupPrice: "3500",
  mgmtPrice: "1500",
  basePrice: "2000",
  commissionPercent: "5",
  commissionTrigger: "closed deals from booked meetings",
  timeFrame: "90 days",
  ctaUrl: "",
  theme: "light",
};

export const REQUIRED_OFFER_FIELDS = [
  "packageName",
  "primaryOutcome",
  "buyerType",
  "niche",
] as const;

export const PRICE_OFFER_FIELDS = [
  "monthlyPrice",
  "setupPrice",
  "mgmtPrice",
  "basePrice",
  "commissionPercent",
] as const;

export const OFFER_FIELD_SECTIONS: OfferFieldSection[] = [
  {
    title: "Basics",
    columns: 2,
    fields: [
      { key: "packageName", label: "Package Name", required: true },
      { key: "primaryOutcome", label: "Primary Outcome", required: true },
      { key: "buyerType", label: "Buyer Type", required: true },
      { key: "niche", label: "Niche", required: true },
      { key: "coreMechanism", label: "Core Mechanism" },
      { key: "toolsOrMethod", label: "Tools or Method" },
      { key: "simpleOutcome", label: "Simple Outcome" },
      { key: "bigObstacle", label: "Big Obstacle" },
      { key: "coreProblem", label: "Core Problem" },
      { key: "ctaUrl", label: "CTA URL" },
    ],
  },
  {
    title: "Pain Points & Symptoms",
    columns: 2,
    fields: [
      { key: "painPoint1", label: "Pain Point 1" },
      { key: "painPoint2", label: "Pain Point 2" },
      { key: "painPoint3", label: "Pain Point 3" },
      { key: "painPoint4", label: "Pain Point 4" },
      { key: "painPoint5", label: "Pain Point 5" },
      { key: "symptom1", label: "Symptom 1" },
      { key: "symptom2", label: "Symptom 2" },
      { key: "symptom3", label: "Symptom 3" },
      { key: "symptom4", label: "Symptom 4" },
      { key: "roleOverloadDetails", label: "Role Overload Details" },
    ],
  },
  {
    title: "Process & Deliverables",
    columns: 2,
    fields: [
      { key: "onboardingFormName", label: "Onboarding Form Name" },
      { key: "workshopLength", label: "Workshop Length" },
      { key: "buildStyle", label: "Build Style" },
      { key: "deliverable1", label: "Deliverable 1" },
      { key: "deliverable2", label: "Deliverable 2" },
      { key: "deliverable3", label: "Deliverable 3" },
      { key: "optionalDeliverable4", label: "Optional Deliverable 4" },
      { key: "clientPreferredWork", label: "Client Preferred Work" },
      { key: "clientPainfulWork", label: "Client Painful Work" },
      { key: "goal1", label: "Goal 1" },
      { key: "goal2", label: "Goal 2" },
      { key: "goal3", label: "Goal 3" },
      { key: "goal4", label: "Goal 4" },
    ],
  },
  {
    title: "Included Blocks",
    columns: 2,
    fields: [
      { key: "deliverableBlock1Title", label: "Block 1 Title" },
      { key: "actionVerb1", label: "Block 1 Action Verb" },
      { key: "component1", label: "Block 1 Component" },
      { key: "outcome1", label: "Block 1 Outcome" },
      { key: "subItemA", label: "Sub Item A" },
      { key: "subItemB", label: "Sub Item B" },
      { key: "subItemC", label: "Sub Item C" },
      { key: "outcomeStatement1", label: "Block 1 Outcome Statement" },
      { key: "deliverableBlock2Title", label: "Block 2 Title" },
      { key: "actionVerb2", label: "Block 2 Action Verb" },
      { key: "component2", label: "Block 2 Component" },
      { key: "outcome2", label: "Block 2 Outcome" },
      { key: "subItemD", label: "Sub Item D" },
      { key: "subItemE", label: "Sub Item E" },
      { key: "subItemF", label: "Sub Item F" },
      { key: "outcomeStatement2", label: "Block 2 Outcome Statement" },
      { key: "deliverableBlock3Title", label: "Block 3 Title" },
      { key: "actionVerb3", label: "Block 3 Action Verb" },
      { key: "component3", label: "Block 3 Component" },
      { key: "toolsOrProcess", label: "Tools or Process" },
      { key: "subItemG", label: "Sub Item G" },
      { key: "subItemH", label: "Sub Item H" },
      { key: "subItemI", label: "Sub Item I" },
      { key: "outcomeStatement3", label: "Block 3 Outcome Statement" },
    ],
  },
  {
    title: "Pricing",
    columns: 2,
    fields: [
      { key: "monthlyPrice", label: "Monthly Price", type: "number" },
      { key: "setupPrice", label: "Setup Price", type: "number" },
      { key: "mgmtPrice", label: "Management Price", type: "number" },
      { key: "basePrice", label: "Base Price", type: "number" },
      { key: "commissionPercent", label: "Commission Percent", type: "number" },
      { key: "commissionTrigger", label: "Commission Trigger" },
      { key: "timeFrame", label: "Time Frame" },
    ],
  },
];
